import '../database_constants.dart';

const ID_PARTICIPANT = "participant_id";
const PARTICIPANT_NAME = "name";
const PARTICIPANT_SURNAME = "surname";
const PARTICIPANT_EDUCATION_LEVEL = "education";
const PARTICIPANT_SEX = "sex";
// const PARTICIPANT_HANDEDNESS = "handedness";
const BIRTH_DATE_PARTICIPANT = "birth_date";

const SCRIPT_CREATE_TABLE_PARTICIPANTS = '''
  CREATE TABLE $TABLE_PARTICIPANTS
(
  $ID_PARTICIPANT INTEGER PRIMARY KEY AUTOINCREMENT,
  $PARTICIPANT_NAME TEXT NOT NULL,
  $PARTICIPANT_SURNAME TEXT NOT NULL,
  $PARTICIPANT_EDUCATION_LEVEL INT CHECK($PARTICIPANT_EDUCATION_LEVEL BETWEEN 1 AND 7),
  $PARTICIPANT_SEX INT CHECK($PARTICIPANT_SEX IN (1, 2)),

  $BIRTH_DATE_PARTICIPANT TIMESTAMP
);

''';
// $PARTICIPANT_HANDEDNESS INT CHECK($PARTICIPANT_HANDEDNESS BETWEEN 1 AND 3),