name: novo_cogni
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  path_provider: ^2.1.0
  flutter_svg: ^2.0.7
  path: ^1.8.3
  equatable: ^2.0.5
  provider: ^6.0.5
  intl: 0.18.1
  get: ^4.6.5
  sqflite_common_ffi: ^2.3.0+2
  flutter_dotenv: ^5.1.0
  crypto: ^3.0.3
  dotenv: ^4.1.0
  record: ^5.0.1
  audioplayers: ^5.2.0
  encrypt: ^5.0.0
  percent_indicator: ^4.2.3
  window_manager: ^0.3.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/folder.svg
    - assets/abstract-user.svg
    - assets/profile-placeholder.png
    - assets/audio/
    - assets/images/
    - assets/task_prompts/
    - assets/test_prompts/
    - .env