import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:intl/intl.dart';
import 'package:novo_cogni/app/domain/entities/tarefa_entity.dart';
import '../../app/data/datasource/avaliacao_local_datasource.dart';
import '../../app/data/datasource/modulo_local_datasource.dart';
import '../../app/domain/entities/avaliacao_entity.dart';
import '../../app/domain/entities/avaliacao_modulo_entity.dart';
import '../../app/domain/entities/modulo_entity.dart';
import '../../app/domain/entities/participante_entity.dart';
import '../../app/domain/repositories/avaliacao_modulo_repository.dart';
import '../../app/domain/repositories/avaliacao_repository.dart';
import '../../app/domain/repositories/modulo_repository.dart';
import '../../app/domain/repositories/participante_repository.dart';
import '../../utils/enums/idioma_enums.dart';
import '../../utils/enums/modulo_enums.dart';
import '../../utils/enums/pessoa_enums.dart';
import '../../utils/enums/tarefa_enums.dart';

class CadastroParticipanteController extends GetxController {
  final ParticipanteRepository _repository;
  final AvaliacaoRepository avaliacaoRepository;
  final ModuloRepository moduloRepository;
  final AvaliacaoModuloRepository avaliacaoModuloRepository;

  CadastroParticipanteController(
      this._repository,
      this.avaliacaoRepository,
      this.moduloRepository,
      this.avaliacaoModuloRepository,
      );

  final nomeCompletoController = TextEditingController();
  final dataNascimentoController = TextEditingController();

  final selectedSexo = Rx<Sexo?>(null);
  final selectedEscolaridade = Rx<Escolaridade?>(null);
  final selectedDate = Rx<DateTime?>(null);
  final selectedLateralidade = Rx<Lateralidade?>(null);
  final selectedIdioma = Rx<Idioma?>(null);

  void selectDate(BuildContext context) async {
    DateTime? pickedDate = await showDatePicker(
      context: context,
      initialDate: selectedDate.value ?? DateTime.now(),
      firstDate: DateTime(1900),
      lastDate: DateTime.now(),
    );

    if (pickedDate != null && pickedDate != selectedDate.value) {
      selectedDate.value = pickedDate;
      dataNascimentoController.text = DateFormat.yMd().format(pickedDate);
    }
  }

  Future<int?> createParticipante(int avaliadorID, List<String> selectedModulos) async {
    var nomeCompleto = nomeCompletoController.text;
    List<String> parts = nomeCompleto.split(' ');

    var nome = parts.first;
    var sobrenome = parts.skip(1).join(' ');

    DateTime? parsedDate =
    DateFormat('yyyy-MM-dd').parse(dataNascimentoController.text);

    ParticipanteEntity novoParticipante = ParticipanteEntity(
      nome: nome,
      sobrenome: sobrenome,
      dataNascimento: parsedDate!,
      sexo: selectedSexo.value!,
      escolaridade: selectedEscolaridade.value!,
    );

    // Assuming that createParticipante returns the ID of the newly created Participante
    int? newParticipanteId = await _repository.createParticipante(novoParticipante);

    if (newParticipanteId != null) {
      // Create the avaliacao entity
      AvaliacaoEntity novaAvaliacao = AvaliacaoEntity(
        avaliacaoID: null, // This will be auto-generated by the database.
        avaliadorID: avaliadorID, // Use the passed avaliadorID here.
        participanteID: newParticipanteId,
      );

      // Create an instance of AvaliacaoLocalDataSource
      AvaliacaoLocalDataSource avaliacaoDataSource = AvaliacaoLocalDataSource();

      // Save the avaliacao entity to the database and get the ID
      int? newAvaliacaoId = await avaliacaoDataSource.create(novaAvaliacao);

      if (newAvaliacaoId != null) {
        // Create the ModuloEntity objects
        List<ModuloEntity> modulos = createModulosEntities(selectedModulos, newAvaliacaoId);

        // Save the ModuloEntity objects to the database
        ModuloLocalDataSource moduloDataSource = ModuloLocalDataSource();
        for (ModuloEntity modulo in modulos) {
          await moduloDataSource.create(modulo);
        }

        // Return the newAvaliacaoId for further use if needed.
        return newAvaliacaoId;
      }

    }

    // Return null if the Participante or Avaliacao creation failed.
    return null;
  }


  Future<ParticipanteEntity?> getParticipant(int id) async {
    return _repository.getParticipante(id);
  }

  Future<List<ParticipanteEntity>?> getAllParticipantes() async {
    return _repository.getAllParticipantes();
  }

  List<ModuloEntity> createModulosEntities(List<String> selectedActivities, int evaluationID) {
    return selectedActivities.map((activity) {
      TarefaEntity tarefa = TarefaEntity(nome: activity,
        status: StatusTarefa.a_realizar,);
      return ModuloEntity(
        date: DateTime.now(),
        score: 0,
        status: StatusModulo.a_iniciar,
        tarefas: [tarefa],
      );
    }).toList();
  }

  Future<bool> saveModulos(List<ModuloEntity> modulos) async {
    ModuloLocalDataSource moduloDataSource = ModuloLocalDataSource();
    bool isSuccess = true;

    for (ModuloEntity modulo in modulos) {
      int? result = await moduloDataSource.create(modulo);
      if (result == null) {
        isSuccess = false;
        break; // Break out of the loop if any save operation fails
      }
    }
    return isSuccess;
  }


  @override
  void onClose() {
    nomeCompletoController.dispose();
    dataNascimentoController.dispose();
    super.onClose();
  }


  Future<void> linkAvaliacaoToModulos(int avaliacaoId, List<int> moduloIds) async {
    for (final moduloId in moduloIds) {
      final avaliacaoModulo = AvaliacaoModuloEntity(
        avaliacaoId: avaliacaoId,
        moduloId: moduloId,
      );

      final int? createdId = await avaliacaoModuloRepository.createAvaliacaoModulo(avaliacaoModulo);
      if (createdId == null) {
        print('Failed to create AvaliacaoModuloEntity for avaliacaoId: $avaliacaoId and moduloId: $moduloId');
        // Optionally, handle the error more robustly here
      }
    }
  }


  Future<bool> createParticipanteAndModulos(int? avaliadorID, List<String> selectedActivities) async {
    // Start a transaction or batch operation if your database supports it
    // Database.startTransaction(); // Pseudocode for starting a transaction

    try {
      // Create the participant and get the evaluationID
      int? evaluationID = await createParticipante(avaliadorID!, selectedActivities);
      if (evaluationID == null) {
        // Handle the error, maybe throw an exception or return false
        // Database.rollbackTransaction(); // Pseudocode for rolling back a transaction
        return false;
      }

      // Create ModuloEntity objects
      List<ModuloEntity> modulos = createModulosEntities(selectedActivities, evaluationID);

      // Save the ModuloEntity objects to the database and collect their IDs
      List<int> moduloIds = [];
      for (var modulo in modulos) {
        int? moduloId = await moduloRepository.createModulo(modulo); // This should return the new ID
        if (moduloId == null) {
          // Handle the error, maybe throw an exception or return false
          // Database.rollbackTransaction(); // Pseudocode for rolling back a transaction
          return false;
        }
        moduloIds.add(moduloId);
      }

      // Link the Avaliacao to the Modulos
      await linkAvaliacaoToModulos(evaluationID, moduloIds);

      // If everything went well, commit the transaction
      // Database.commitTransaction(); // Pseudocode for committing a transaction
      return true;
    } catch (e) {
      // If there was an error, rollback the transaction
      // Database.rollbackTransaction(); // Pseudocode for rolling back a transaction

      // Handle the exception, log it, or rethrow
      print('An error occurred: $e');
      return false;
    }
  }




  void printFormData() {
    print('Nome Completo: ${nomeCompletoController.text}');
    print('Data de Nascimento: ${dataNascimentoController.text}');
    print('Sexo: ${selectedSexo.value == Sexo.homem ? 'Homem' : (selectedSexo.value == Sexo.mulher ? 'Mulher' : 'Not Selected')}');
    print('Escolaridade: ${selectedEscolaridade.value?.toString().split('.').last ?? 'Not Selected'}');
    print('Date: ${selectedDate.value?.toIso8601String() ?? 'Not Selected'}');
    print('Lateralidade: ${selectedLateralidade.value?.toString().split('.').last ?? 'Not Selected'}');
    print('Idioma: ${selectedIdioma.value?.toString().split('.').last ?? 'Not Selected'}');
  }

}
