import '../database_constants.dart';
import '../evaluation/evaluation_constants.dart';
import '../module/module_constants.dart';

const ID_MODULE_INSTANCE = "module_inst_id";
const ID_MODULE_FK = ID_MODULE;
const ID_EVALUATION_FK = ID_EVALUATION;
const MODULE_INSTANCE_STATUS = "status";

const SCRIPT_CREATE_TABLE_MODULE_INSTANCES = '''
  CREATE TABLE $TABLE_MODULE_INSTANCES
(
  $ID_MODULE_INSTANCE INTEGER PRIMARY KEY AUTOINCREMENT,
  $ID_MODULE_FK INTEGER NOT NULL,
  $ID_EVALUATION_FK INTEGER NOT NULL,
  $MODULE_INSTANCE_STATUS INT NOT NULL CHECK($MODULE_INSTANCE_STATUS >= 1 AND $MODULE_INSTANCE_STATUS <= 3),
  FOREIGN KEY ($ID_MODULE_FK) REFERENCES $TABLE_MODULES($ID_MODULE),
  FOREIGN KEY ($ID_EVALUATION_FK) REFERENCES $TABLE_EVALUATIONS($ID_EVALUATION)
)
''';
